#!/usr/bin/env bash

# Check if an IP address was passed as an argument
if [ -z "$1" ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Run ping command with the IP address as an argument
ping -c 5 "$1"

